modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://github.com/xfacthd/RainbowSixSiegeMC/issues" #optional
license="LGPLv3"

[[mods]] #mandatory
    modId="r6mod" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="R6Mod" #mandatory
    # A URL to query for updates for this mod. See the JSON update specification <here>
    #updateJSONURL="http://myurl.me/" #optional
    # A URL for the "homepage" for this mod, displayed in the mod UI
    #displayURL="http://example.com/" #optional
    logoFile="r6mod.png" #optional
    authors="XFactHD" #optional
    description='''
    '''

[[dependencies.r6mod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34.0.9,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.r6mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
